### ISSUE TITLE
Support sealing concrete classes

### ISSUE THREAD

**Issue by stof** [jiripudil/phpstan-sealed-classes#1]
Currently, this extension only supports sealing abstract classes or interfaces. Is there any reason to have that restriction ?

In the upcoming v2 of scssphp, I have a use case that would require sealing a concrete class. Among our [Value classes](https://github.com/scssphp/scssphp/tree/master/src/Value), our intent is that they should all be either final or sealed (no custom child classes are intended to be supported). But our `SassList` class is both a concrete class (representing normal Sass lists) and the parent of the `SassArgumentList` class (representing a special kind of list). Making `SassList` a sealed class would allow to represent that intent, but it is not supported by your package currently (disclaimer: scssphp does not use your package yet, but our other classes that would be marked as sealed are abstract so this would not be a blocker).

Supports in other languages:
- Dart allows sealing concrete classes
- Hack allows sealing concrete classes
- Java allows sealing concrete classes
- the declined PHP RFC about sealed classes was also allowing sealing concrete classes
- Kotlin makes sealed classes abstract (without requiring an `abstract` keyword), thus forbidding sealing concrete classes

**Comment by jiripudil** [comment]
Hello,

honestly, the main reason is that I drew inspiration from Kotlin and it covered all my use cases.

There _is_ some rationale behind preferring abstract classes, though: the restriction of type hierarchy is only a small part of the picture. I find great value in one particular thing that Kotlin does and other languages you've mentioned seem to overlook: [exhaustiveness check](https://jiripudil.cz/blog/true-power-of-sealed-classes). This extension can do it too by hooking into PHPStan's type subtraction mechanisms.

That being said, I believe it should be possible to lift the restriction on abstract classes. With the way class instances are represented and how their subtyping is implemented in PHPStan, I'm afraid you'll lose this exhaustiveness check, but I don't see it as a problem, just a trade-off worth mentioning.

I'll look into the implementation details soon™.

**Comment by stof** [comment]
Well, in my case, `SassArgumentList` is a very specific kind of `SassList` (which does not need a different handling than SassList in 99% of the cases differentiating by type of values). So the exhaustiveness checks would generally happen on the `Value` abstract class, not on SassList.
So I'm fine on losing the benefit shown in your blog post for the SassList case (which I also lose if I cannot mark it as sealed anyway, while also losing other benefits like telling consumers of my package that they should not extend it). Thus, this exhaustiveness check will not be lost for abstract sealed classes AFAICT.
